version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /root/dev/caddy/certs/server.crt:/var/lib/postgresql/data/server.crt
      - /root/dev/caddy/certs/server.key:/var/lib/postgresql/data/server.key
    command: >
      -c ssl=on
      -c shared_buffers=4GB
      -c work_mem=1GB
      -c effective_cache_size=8GB
      -c maintenance_work_mem=1GB
      -c checkpoint_timeout=15min
      -c wal_buffers=16MB
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=6
      -c random_page_cost=1.1 -c seq_page_cost=1.0
      -c min_wal_size=1GB 
      -c max_wal_size=4GB
      -c shared_preload_libraries=pg_prewarm











    restart: unless-stopped
    networks:
      - caddy
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    environment:
      - CADDY_INGRESS_NETWORK=caddy
    networks:
      - caddy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  populateTransferEvents:
    container_name: populateTransferEvents
    image: registry.digitalocean.com/hexlive/liquidity-finder:latest
    restart: unless-stopped
    volumes:
      - /opt/.env:/opt/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      options:
        max-size: "10m"
    command: /app/cmd/start populateTransferEvents

  processTokenAmounts:
    container_name: processTokenAmounts
    image: registry.digitalocean.com/hexlive/liquidity-finder:latest
    restart: unless-stopped
    volumes:
      - /opt/.env:/opt/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      options:
        max-size: "10m"
    command: /app/cmd/start processTokenAmounts

  gatherPairs:
    container_name: gatherPairs
    image: registry.digitalocean.com/hexlive/liquidity-finder:latest
    restart: unless-stopped
    volumes:
      - /opt/.env:/opt/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      options:
        max-size: "10m"
    command: /app/cmd/start gatherPairs

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ports:
      - "6379:6379"
    ulimits:
      memlock: -1
    volumes:
      - /root/dev/caddy/dragonfly-data:/data
    command: >
      --maxmemory 1g
      --dir /data
      --snapshot_cron "0 1 * * *"
      --requirepass ${DRAGONFLY_PASSWORD}
    restart: unless-stopped
    networks:
      - caddy

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    expose:
      - 9000
    networks:
      - caddy

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:1.5.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --include-stopped --interval 30 -v populateTransferEvents processTokenAmounts gatherPairs
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
volumes:
  pgdata:
  caddy-data:
  caddy-config:
  portainer_data:

networks:
  caddy:
    external: true
