name: db01
services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    environment:
      - CADDY_INGRESS_NETWORK=caddy
    networks:
      - caddy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${DB_DATA_DIR}:/var/lib/postgresql/data
    command: >
      -c ssl=off
      -c shared_buffers=4GB
      -c work_mem=32MB
      -c effective_cache_size=8GB
      -c maintenance_work_mem=1GB
      -c checkpoint_timeout=15min
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c wal_level=minimal
      -c wal_compression=on
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=6
      -c random_page_cost=1.1 -c seq_page_cost=1.0
      -c min_wal_size=1GB 
      -c max_wal_size=8GB
      -c max_wal_senders=0
      -c shared_preload_libraries=pg_prewarm
      -c synchronous_commit=off
      -c fsync=off

    restart: unless-stopped
    depends_on:
      - caddy
    networks:
      - caddy

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    expose:
      - 9000
    networks:
      - caddy
    depends_on:
      - caddy

volumes:
  caddy-data:
  caddy-config:
  portainer_data:

networks:
  caddy:
    external: true
